### ISSUE TITLE
Do more DSA!

### ISSUE THREAD

**Issue by anirban-oss** [anirban-oss/computer-science-memories#4]
More DSA! More DSA! More DSA! More DSA! More DSA! More DSA! More DSA! More DSA! More DSA! More DSA! More DSA! More DSA! More DSA! More DSA! More DSA! More DSA! More DSA! More DSA! More DSA! More DSA! More DSA! More DSA! More DSA! More DSA! More DSA! More DSA! More DSA! More DSA! More DSA! More DSA! More DSA! More DSA! More DSA! More DSA! More DSA! More DSA! More DSA! More DSA! More DSA! More DSA! More DSA! More DSA! More DSA! More DSA! More DSA! More DSA! More DSA! More DSA! More DSA! More DSA! More DSA! More DSA! More DSA! More DSA! More DSA! More DSA! More DSA! More DSA! More DSA! More DSA! More DSA! More DSA! More DSA! More DSA! More DSA! More DSA! More DSA! More DSA! More DSA! More DSA! More DSA! More DSA! More DSA! More DSA! More DSA! More DSA! More DSA! More DSA! More DSA! More DSA! More DSA! More DSA! More DSA! More DSA! More DSA! More DSA! More DSA! More DSA! More DSA! More DSA! More DSA! More DSA! More DSA! More DSA! More DSA! More DSA! More DSA! More DSA! More DSA! More DSA! More DSA! More DSA! More DSA! More DSA! More DSA! More DSA! More DSA! More DSA! More DSA! More DSA! More DSA! More DSA! More DSA! More DSA! More DSA! More DSA! More DSA! More DSA! More DSA! More DSA! More DSA! More DSA! More DSA! More DSA! More DSA! More DSA! More DSA! More DSA! More DSA! More DSA! More DSA! More DSA! More DSA! More DSA! More DSA! More DSA! More DSA! More DSA! More DSA! More DSA! More DSA! 

- [ ] More DSA!

**Comment by Parmesh119** [comment]
**@anirban-oss, Hope you are fine.
Can I add some DSA questions and answers to them?**

**Comment by anirban-oss** [comment]
this is so kind, you are very welcome to add them. thank you.
